echo ""
echo "*********************************************************"
echo "Did you run"
echo "src\test\java\jl\project\ConfigurationUtility.java"
echo "prior to starting the e2e script ?"
echo "*********************************************************"
read -p "Press the [Enter] key to continue..."